### ISSUE TITLE
Bug: Querying gtfs_rt.vehicle_positions fails for most queries

### ISSUE THREAD

**Issue by edasmalchi** [cal-itp/data-infra#1051]
**Describe the bug**
Queries on the new gtfs_rt.vehicle_positions table seem to fail almost all of the time. With a tiny limit value ~100, the query may run after several tries so perhaps something to do with timing/continuous loading+updating of the table? Larger queries consistently fail.

**To Reproduce**
1. Try a query on gtfs_rt.vehicle_positions, for example 
```
SELECT * FROM `cal-itp-data-infra.gtfs_rt.vehicle_positions`
WHERE calitp_itp_id = 300 LIMIT 1000
```
2. Observe various BigQuery JSON parse/process errors

**Expected behavior**
Query returning a valid table without errors.

**Additional context**
BigQuery errors:
```

Error while reading table: cal-itp-data-infra.gtfs_rt.vehicle_positions, error message: JSON parsing error in row starting at position 0: Could not convert value 'string_value: "vehicle_193"' to integer. Field: id; Value: vehicle_193
Error while reading table: cal-itp-data-infra.gtfs_rt.vehicle_positions, error message: JSON processing encountered too many errors, giving up. Rows: 1; errors: 1; max bad: 0; error percent: 0
Error while reading table: cal-itp-data-infra.gtfs_rt.vehicle_positions, error message: JSON parsing error in row starting at position 0: Could not convert value 'string_value: "t_2062901_b_33847_tn_8"' to integer. Field: tripId; Value: t_2062901_b_33847_tn_8
Error while reading table: cal-itp-data-infra.gtfs_rt.vehicle_positions, error message: JSON processing encountered too many errors, giving up. Rows: 2; errors: 2; max bad: 0; error percent: 0
Error while reading table: cal-itp-data-infra.gtfs_rt.vehicle_positions, error message: JSON parsing error in row starting at position 0: No such field: vehicle.currentStopSequence.
Error while reading table: cal-itp-data-infra.gtfs_rt.vehicle_positions, error message: JSON processing encountered too many errors, giving up. Rows: 3; errors: 3; max bad: 0; error percent: 0 
```

Another BigQuery error via calitp.py `query_sql`
```
BadRequest: 400 Error while reading table: cal-itp-data-infra.gtfs_rt.vehicle_positions, error message: JSON parsing error in row starting at position 0: No such field: vehicle.currentStopSequence.
```

**Comment by lauriemerrell** [comment]
cc @atvaccaro -- I do not think that this is related to table size, I think the issue is that BigQuery is having problems auto-detecting the schema from the JSON (as opposed to the prior rectangled data that was being loaded from parquet). See [this doc](https://cloud.google.com/bigquery/external-table-definition#creating_a_table_definition_using_schema_auto-detect) for some info on schema auto-detection.

I suspect we will have to make our external table creation (ex[ `external_vehicle_positions.sql`](https://github.com/cal-itp/data-infra/blob/main/airflow/dags/rt_loader/external_vehicle_positions.sql)) more precise and actually specify fields. 

Based on the example errors shown here, it seems to have decided that IDs need to be integers (don't think they actually do); also may have decided on a subset of fields that doesn't account for things like `currentStopSequence`. 

@edasmalchi am I correct in assuming that you're trying to get access to the new San Diego data, and that's why you specifically need the new table and can't use the legacy one that Andrew spun out? If so, I wonder if we can try to generate some San Diego parquet files for you as a stopgap if needed.

**Comment by edasmalchi** [comment]
Thanks @lauriemerrell! 

That's correct, our presentation to District 11 is not until March 1 but since this is new data it would be ideal to have plenty of time to work with it to ensure we present something solid.

If it's not too much trouble, a parquet of a couple days worth of San Diego MTS (278) and NCTD (226) data would be great. Though of course we just started ingesting SDMTS last night so that wouldn't be possible in any case until Thursday. Perhaps it's also possible to fix the broader issue by then?

**Comment by lauriemerrell** [comment]
Thanks @edasmalchi, I think @atvaccaro and I probably need to discuss. We can keep you updated and figure out a way to get you access to the data one way or the other by Thursday.

#### General notes about this issue
A few other places that we define external tables in our pipeline do explicitly declare a schema:
* Most of `gtfs_schedule_history` uses `ExternalTable` operators to define schemas for CSVs ([example](https://github.com/cal-itp/data-infra/blob/main/airflow/dags/gtfs_schedule_history/calendar.yml))
* The external tables for the validation data in `rt_loader` explicitly declare JSON schemas using a SqlQueryOperator -- this is probably the way we'll want to go, this use case is very similar ([example](https://github.com/cal-itp/data-infra/blob/main/airflow/dags/rt_loader/external_validation_vehicle_positions.sql))

Biggest questions I have are:
1. How to make sure everything is appropriately nullable? (In the GTFS schedule pipeline we explicitly make sure that all the CSVs that are being loaded into the external tables do have all the columns that we load. However it does look like [nullable is the default](https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#TableSchema) so maybe this is fine.) 
2. Do we need to worry about different versions of the GTFS RT spec here? (How different are message structures across versions 😓)
