### ISSUE TITLE
Bug: GTFS-RT Archiver has thread fetcher exception that sometimes results in truncated downloaded file 

### ISSUE THREAD

**Issue by Nkdiaz** [cal-itp/data-infra#1087]
**Describe the bug**
While working on https://github.com/cal-itp/data-infra/issues/1010 I noticed that several files had logged errors "Exception in thread fetcher 278/0/gtfs_rt_vehicle_positions_url" in the `std.error` log but when you looked at the timeframe, it still generated completed write timestamps in `std.out`. Upon further research, I am able to see the file as dowloaded during that timeframe in google storage. But when you open that file and compare it to an earlier timepoint that did not have a thread fetcher exception it is severally truncated. 
Looking at a file from 02/08 for calitp 278 has (4214 lines) vs. 02/07 (63187 lines)
Several of the other files that have exceptions do not have the file in the download bucket for the days where the exception occurred. For example "Exception in thread fetcher 273/0/gtfs_rt_vehicle_positions_url".
Upon further research, 
So we are working on the assumption that on days where the feed exception occured, then the downloaded data is likely to be 

**Expected behavior**

**Additional context**
An additional question is if this is an infrastructure problem or a corrupt data problem.
My instinct is that is is not a systemic thing, for 273, it has only generated that error 3 times (2/13,2/10,12/22) since the table was created on dec.15 during different times of the day (8pm vs. 2am)

This may be linked to differences in the google cloud storage `rt `vs. `rt- processed` buckets. Further research is needed to 
1. determine how prevalent this is (is this new? has it been happening all along but we didn't log it?)
2.  Determine how we want to treat an exception as resolved (if its internal retry do we still count it as an error? how can we tell if it was handled within the library?)
3. How can we tag files that have exceptions so we can either a-backfill or b-delete entries that are likely incorrect

**Comment by Nkdiaz** [comment]
![image (1)](https://user-images.githubusercontent.com/32888103/154115938-030ee31a-9d5c-445d-80c4-abd436f6f241.png)

**Comment by lauriemerrell** [comment]
I think this is causing issue #278. We have a lot of missing vehicle positions data for San Diego and it seems to be an archiver issue

**Comment by lottspot** [comment]
@Nkdiaz can you please post a log query link to help facilitate investigating the nature of these exceptions?

**Comment by lottspot** [comment]
Found a window where an exception shows up: https://cloudlogging.app.goo.gl/RzWZ4upyBH1ZhqMw8

**Comment by lauriemerrell** [comment]
Update: We are pretty sure that the missing data for `itp_id` 278 was NOT caused by these fetcher exceptions. I'm looking into whether there is missing data associated with the affected IDs, which @Nkdiaz identified as: 
![image](https://user-images.githubusercontent.com/55149902/154139452-f6d7140d-d545-4523-9445-711ea5958d7a.png)

Based on this query (modified to select distinct ITP IDs):
`SELECT textPayload, timestamp,
regexp_extract(textPayload, "fetcher ([0-9]+)")AS calitp_itp_id,
regexp_extract(textpayload,"fetcher ([0-9]+/[0-9]+/?[a-zA-Z0-9\\.\\_\\-]+)?") AS feed_file_name,
 FROM cal-itp-data-infra.gtfs_rt_logs.stderr
WHERE textPayload LIKE "%fetcher%" ORDER BY calitp_itp_id desc`

**Comment by lottspot** [comment]
Entry of interest in the above linked log sample:
<img width="1063" alt="Screen Shot 2022-02-15 at 2 48 56 PM" src="https://user-images.githubusercontent.com/2199417/154140662-129b8e8c-803a-4a19-9472-d71191112aaa.png">

**Comment by lottspot** [comment]
A lightbulb: I actually believe these broken pipe exceptions are due to a (mild) regression introduced in the refactor. 

[within PoolFetcher](https://github.com/cal-itp/data-infra/blob/4bfa178c19fe7b68704cb67d3840e5ba72962e72/services/gtfs-rt-archive/src/gtfs_rt_archive/threads/fetcher.py#L90-L95):

```python
                self.fetch(txn)
                self.logger.debug("[txn {}] completed fetch".format(txn["id"]))
                if hasattr(txn["input_stream"], "read"):
                    self.wq.put(txn)
                else:
                    self.logger.warn("[txn {}] no data fetched".format(txn["id"]))
```

This check for a "readable" input stream _used to be_ sufficient, because the `fetch()` method would return a readable stream if a HTTP request was successful, and `None` if there was an error. _Now_, the `fetch(txn)` method does not return any value, and simply [mutates the txn dict which it is passed](https://github.com/cal-itp/data-infra/blob/4bfa178c19fe7b68704cb67d3840e5ba72962e72/services/gtfs-rt-archive/src/gtfs_rt_archive/threads/fetcher.py#L63-L73). I believe that the consequence here is that whether or not a fetcher's HTTP request is successful, the txn *always* has a "readable" (but broken, in the case of failed requests) stream attached to it, causing it to be blindly placed onto the write queue in all cases. I think this can also explain things like bad/truncated feeds showing up in the data bucket.

The solution I would personally choose here would be to set `txn["input_stream"] = None` during the exception handling phase of the fetcher.

**Comment by lottspot** [comment]
`http.client.RemoteDisconnected` is currently an exception which can happen within `PoolFetcher.fetch(txn)` which is not currently being handled and probably ought to be

**Comment by lottspot** [comment]
Identifying any other connection-related errors which may manifest themselves as exceptions would be a valuable exercise to take up alongside these exception handling changes.

**Comment by atvaccaro** [comment]
I wonder if a goroutine-ish pattern could be useful here, i.e. firing off single-execution threads to handle the writes.

Non-exiting threads could be problematic, but it might simplify the overall architecture while preserving some of the concurrency.

Side note, will multiple writers even work right now? If they consume the stream via `read()`?

**Comment by lottspot** [comment]
> I wonder if a goroutine-ish pattern could be useful here, i.e. firing off single-execution threads to handle the writes.

That could work too. Might be a heavier lift, but any pattern which treats I/O threads as things which are expected to die at some point is a pattern which would suit our needs well. My only concern with that specific approach is that we're not in fact dealing with goroutines here-- these are true OS threads, which could have latency implications. This concern is admittedly theoretical in nature-- it may be the case that spawning all new threads on each tick is "fast enough" for our needs. Only testing could tell us for sure.

> Non-exiting threads could be problematic, but it might simplify the overall architecture while preserving some of the concurrency.

The existing `ThreadPool` class is well suited to solving a problem of this nature. It maintains an internal table of all `Thread` instances which it has spawned, which means it has all of the necessary primitives to do things like check if threads are running and shut down running threads on demand.

> Side note, will multiple writers even work right now? If they consume the stream via `read()`?

Multiple writers would theoretically work fine-- the stream reference is placed onto a thread-safe write queue, which the writer picks up from there. Multiplexing that should be as simple as spawning multiple writers which consume the same write queue, though I have admittedly never tested this.

**Comment by lottspot** [comment]
> if a fetcher dies, it will be respawned by the ThreadPool on the next tick

@atvaccaro pointed out to me that this is actually not observed to be happening in practice. A double check of the source confirms the observation; these threads are _not_ respawned on every tick. Rather, [they are respawned on every "reload" event](https://github.com/cal-itp/data-infra/blob/4bfa178c19fe7b68704cb67d3840e5ba72962e72/services/gtfs-rt-archive/src/gtfs_rt_archive/threadpool.py#L57). `ThreadPool.reconcile()` should definitely be called on every tick; this would make fetchers far more resilient to exceptions

**Comment by atvaccaro** [comment]
This is no longer relevant
