### ISSUE TITLE
Feature - GTFS Schedule: Create tables for rows changed/removed by cleaning 

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1093]
**Is your feature request related to a problem? Please describe.**
With the current work on whitespace trimming (#1022 etc.) and duplicate removal (#1079 etc.), we are making our warehouse data more usable for analysis by standardizing data. This is vital to ensure that analysts can rely on the data in `views`. 

However, it also risks suppressing problems that agencies should be aware of and, ideally, fix. In general, these issues should be caught by the GTFS validator (for example, Foothill Transit *is* throwing a `more_than_one_entity` warning for `feed_info.txt`). However, it seems prudent for us to explicitly identify data we are modifying so that can be cross-referenced with validations.

**Describe the solution you'd like**
We should create some kind of cleaning validations table (distinct from GTFS validator output) to retain information about fields that were affected by the cleaning process. For example, in #1079, we should create a table that exposes the duplicate `feed_info` row.

**Describe alternatives you've considered**
Relying on the GTFS validator to expose issues. However, we have seen in the whitespace discussion that there are cases where we will trim whitespace that is not called out by the validator as a problem.

**Additional context**
There is some precedent for `validation_` views in the Payments pipeline that we could potentially follow as a model.

**Comment by evansiroky** [comment]
> **Describe alternatives you've considered**
> Relying on the GTFS validator to expose issues.

This may not be that bad of an alternative.

**Comment by evansiroky** [comment]
> > This may not be that bad of an alternative.
> 
> I think it's fine in the short term but long term I think we might want to capture adjustments separately for the following reasons:
> 
> 1. Confirm that the validator is actually catching all the issues that our cleaning is catching

If the validator isn't catching something, I think it'd be best to try to fix the validator so it does catch the thing.

> 2. For whitespace in particular, we know that the validator will NOT capture everything. So then it's a question of whether we want to flag things to agencies that aren't caught by the validator.

For this particular issue, there is sort of a "common knowledge" assumption that field values get trimmed before being inserted into the database. If there are other items like this that the validator doesn't catch, we need to evaluate on a case-by-case basis whether it really is a lacking of the validator or something we can deal with.

> 3. ^ Taking the above one step further, if we add any further "cleaning" here, this kind of thing would probably be useful for assessing any potential _new_ validations or best practices we might want to propose for the validators.

I think the proposing of changes to the validators could happen without creating a table like described.

**Comment by evansiroky** [comment]
> What I was thinking is that if we start doing trimming and duplicate detection automatically, it will be hard for us to catch any potential validator misses because we will be suppressing them from our final data as well. So it would be hard for us to notice these (I agree that we'd want to fix the validator, but I'm wondering how we'd know we _need_ to fix the validator if we don't have an independent check on some of these things.)

So far, these are 2 items that are requiring code modifications to our pipeline. Both of them should probably be permanent data massaging fixes since each will help all data get processed, thus unblocking a wide variety of users from being able to analyze the data. For our purposes of doing various analyses, we do expect eventual error-free data. If we were making a GTFS editor this would be a different story and we would perhaps want to be capturing some incomplete data that someone could keep on editing.

Regarding knowing when we need to fix the validator, it seems like whenever we have items like https://github.com/cal-itp/data-infra/issues/498 and https://github.com/cal-itp/data-infra/issues/1079, we have come to the conclusion that we do need to massage our data to be able to analyze those items. However, both of those times, we concluded that the validator didn't need a fix.

I don't think it would add much value to add new software to our pipeline to capture the faulty data since the faulty data may not provide much use. Whatever thing breaks our pipeline in the future will be something we'll want to evaluate. We'll figure out if these problems are covered by the validator and if they are not we need to decide whether we should propose a fix. 

> In cases like SacRT (where they have whitespace in some cases but not in others), does that mean we still wouldn't even notify the agency? It still seems like it would be better for agencies to fix these cases, even if it's not a formal violation.

For this particular use-case, since there is an assumption that GTFS-consuming applications will trim whitespace, I don't think it is worth taking the time to notify them of this problem.

**Comment by lauriemerrell** [comment]
Don't think this ticket is applicable any longer in v2 warehouse
