### ISSUE TITLE
Adopt SQL Style Guide

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-infra#1120]
nit: is this intended to be an inner join? if so, could it be made explicit?

_Originally posted by @atvaccaro in https://github.com/cal-itp/data-infra/pull/1115#discussion_r813405497_

**Comment by mjumbewu** [comment]
@atvaccaro calling out `inner join` explicitly seems a little weird to me. However, that is admittedly because I never do it (because it's not strictly necessary and `inner join` is always the default) and change can be weird. Maybe, for the sake of saving some nits, we should pick a SQL style guide so that we're all using the same yard stick.

Some likely decent choices:
* [Mozilla's Style Guide](https://docs.telemetry.mozilla.org/concepts/sql_style.html)
* [DBT Lab's Internal Corporate Style Guide](https://github.com/dbt-labs/corp/blob/master/dbt_style_guide.md)
* [GitLab's Internal Style Guide](https://about.gitlab.com/handbook/business-technology/data-team/platform/sql-style-guide/)

_(I think all of the above mention being explicit about joins, so I may end up changing the code anyway, but it feels better when I can just blame it on the style guide :wink:)_

Maybe, down the line, we could even add [SQLFluff](https://github.com/sqlfluff/sqlfluff) to our pre-commit step.

**Comment by atvaccaro** [comment]
yes! would love to use sqlfluff. We roughly followed the dbt guide (except for trailing commas) at Alto, so that's where I'm coming from.

**Comment by holly-g** [comment]
Sqlfluff has been implemented.
