### ISSUE TITLE
GTFS RT: Implement Metric labels for Prometheus/Grafana

### ISSUE THREAD

**Issue by Nkdiaz** [cal-itp/data-infra#1133]
To aid in infrastructure reliability and scalability we are implementing Prometheus to scrape metrics from instrumented jobs and visualizing them on the Grafana dashboards. In order to track metrics we need to add labels to the code in GTFS RT that signals prometheus to measure that particular thing.
Some of the things we might want to measure:

- Threading
- Downloading (ex: request times)
- Uploading
- Failure (ex: when a metric violates a threshold)
- Success (ex: per url what is the success rate)

There should be discussion on the particulars of the metrics (i.e what are our thresholds) and how it interacts with the prometheus Alertmanager.

**Comment by atvaccaro** [comment]
I definitely recommend reading https://prometheus.io/docs/practices/naming/ so we can follow best practices at the start. Some of this may be a bit tricky since the request lives in a separate thread than the `read()` on the response (will defer to @lottspot on the specifics here).

At minimum I think the following would be useful (all of these should have the ITP ID and URL ID)
1. A request, with actual URL
2. A response with status code
3. Finished write, labeled with status, file size, etc.
4. Transaction completion (which we won't have for errors, unless we are better about tracing context)

**Comment by holly-g** [comment]
Putting this on hold (`icebox`) while we re-do the infrastructure

**Comment by atvaccaro** [comment]
This is done!
