### ISSUE TITLE
GTFS RT: Vehicle positions mart models -- implement position cleaning for monotonic progress along route shape

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1196]
After we have initial vehicle positions mart models available, we want to experiment with bringing some of @edasmalchi's existing geoprocessing work into the warehouse itself. 

One such item is cleaning the data such that positions update monotonically along the route; i.e., position updates do not show the vehicle going backwards. 

This will be a delicate operation:
* We need to see if it can be implemented in SQL (we assume not and that this may require a Python microservice)
* We need to be careful about the assumptions/bias that this will introduce; if we drop rows that show "backwards noise" with no adjustments on forward progress, we are biasing the data toward forward motion. We need to be mindful of this and put guardrails about how much such cleaning we are willing to do before we declare the data overall unusable or corrupt.
* We need to make it very clear that this data has had these assumptions imposed on it; tables or columns containing this adjusted data should be labeled as such (perhaps with a prefix like `est_` or `adj_` or similar indicating that it has been manipulated.
* We need to document the adjustment process very clearly and explicitly in the model documentation so that users understand the assumptions that have been imposed.

**Comment by edasmalchi** [comment]
I've taken a very preliminary look at what's actually getting dropped in my current implementation of this cleaning step. I've only spot-checked a couple of trips from different operators, but it seems like "backwards noise" is relatively rare -- less than 5% of the raw position updates.

Far more common (and also currently dropped at the same step) are updates that have a later header timestamp and vehicle timestamp, but show exactly the same position. This makes sense to me since transit vehicles stop all the time for durations longer than the (usual) 20 seconds between pings -- whether at a bus stop or traffic signal. Even some longer stops could be expected -- for example it can easily take 3-5 minutes to board a wheelchair user, or a bus may be waiting at a schedule timepoint.

**Comment by edasmalchi** [comment]
For SamTrans (290) on Feb 8, the median backwards noise value is only 4.3 meters. That said, the average is 460 meters so there appear to be some high outliers. 80th %ile is 282 meters.

For AC Transit (4) on Feb 8, median 76 meters, average 507 meters, 80th %ile 380 meters.

I'll keep looking into this, I'm not sure how much of this has to do with the underlying data vs. applying a fairly naive algorithm to complicated shapes. For example I found one where the data looks mostly ok but the route was self-intersecting (those darn loops!) and my code dropped all of those...

**Comment by lauriemerrell** [comment]
This is still an open need in the warehouse, I believe @edasmalchi and @tiffanychu90 have done a lot of work on this on the notebook analysis side, unclear what the goals/timeline would be to get it into the warehouse. Would probably require using Python models in dbt.
