### ISSUE TITLE
Metabase Question: Which GTFS Schedule feeds have zero service hours in the future?

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-infra#1206]
## User Story

**As a** research data analyst,
**I want to** know what agency GTFS Schedule URLs have downloaded successfully, but their data indicates that in the future zero service hours are scheduled to occur,
**so that** I can properly categorize which transit agencies are having problems with GTFS quality
**and so that** I can know which transit agencies I need to reach out to about expired feeds

For this user story, only the GTFS Schedule and not the GTFS Realtime URLs are considered.

## Acceptance Criteria

**Given** the data describing transit operations within successfully downloaded GTFS Schedule datasets in the nightly pipeline,
**When** the [Catastrophic GTFS Errors Dashboard](https://dashboards.calitp.org/dashboard/46-catastrophic-gtfs-errors-dashboard) is opened,
**Then** a table should be shown that lists out all GTFS Schedule URLs that have zero future service hour and when the last service date occurred according to the schedule data and sorted by descending number of days since last service

**Example:**

Something like the following table should be shown:

|Agency|URL|Number of Days of Zero Service|Last Service Date|
|--|--|--|--|
| Fresno County Rural Transit Agency | http://data.trilliumtransit.com/gtfs/fresnocounty-ca-us/fresnocounty-ca-us.zip | 831 | 2020-01-01 |
| Plumas Transit Systems | http://data.trilliumtransit.com/gtfs/plumas-ca-us/plumas-ca-us.zip | 528 | 2020-10-30 |
...

**Comment by Nkdiaz** [comment]
Metabase dashboard is available at the following link: 
https://metabase.k8s.calitp.jarv.us/question/390-which-gtfs-schedule-feeds-have-zero-service-hours-in-the-future

**Comment by evansiroky** [comment]
This issue should not be considered resolved. On the date of June 8, 2022, the following transit agencies were not showing up in the question when they should have:

* Plumas Transit
* Manteca Transit

The above 2 agencies represent a non-exhaustive list.

**Comment by lauriemerrell** [comment]
Fixed. Looks like Plumas and Manteca (and a few other feeds) have no service at all in `gtfs_schedule_fact_daily_service`, so the relevant new columns in `fact_daily_feeds` are simply null. I updated the Metabase question to include that as a condition and they are now appearing in the dashboard. The `# days` column is null but that basically indicates that they have no service at all in the period covered by our data. I will close again. 

If it is vital to have # days since service for these, can we open a new ticket? That would involve refactoring our `fact_daily_service` table which would be a bigger lift.
