### ISSUE TITLE
Reorganize Amplitude data in GCS

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/data-infra#1240]
Part of the work for #960.

See [this comment](https://github.com/cal-itp/data-infra/pull/1239#issuecomment-1076666810) from @atvaccaro for details

## Tasks

* [x] Update the [operator](https://github.com/cal-itp/data-infra/blob/feat-amplitude-operator/airflow/plugins/operators/amplitude_to_flattened_json.py#L123) to pass a `bucket` parameter, equal to `ingest_amplitude_raw_dev` or `ingest_amplitude_raw_prod` depending on the value of `is_development()`
* [x] Update the [loader](https://github.com/cal-itp/data-infra/blob/feat-amplitude-operator/airflow/dags/amplitude_benefits_loader/jsonl_bigquery.sql#L69) to load from the new bucket

**Comment by thekaveman** [comment]
@atvaccaro notes:

>> I would consider making `ingest_amplitude_raw_dev` and `ingest_amplitude_raw_dev_prod` potentially.

> Oh and to follow-up on this, I would use [`is_development()` in calitp-py](https://github.com/cal-itp/calitp-py/blob/main/calitp/config.py#L17) to pick between the two.

**Comment by lauriemerrell** [comment]
A bit more context here-- the `AirtableToWarehouse` operator [calls](https://github.com/cal-itp/data-infra/blob/main/airflow/plugins/operators/airtable_to_warehouse.py#L126) [calitp.save_to_gcs](https://github.com/cal-itp/calitp-py/blob/main/calitp/storage.py#L16), which does still call `get_bucket` under the hood.

So, @atvaccaro and I do think it would be great if you all write to a brand new bucket -- that is very much aligned with the future direction of the bucket structure and will save a migration later. However as Andrew mentioned you would probably need to look to `calitp.is_development` directly in a new pattern and not be able to rely on the existing `save_to_gcs` or `get_bucket` since those are hard-coded to `gtfs-data` and `gtfs-data-test`.

(TLDR: We appreciate the openness to moving to the new paradigm but it does come with some extra work since we haven't built out as much support for that direction yet; if there's anything we can do to help make that clearer or easier please let us know.)

**Comment by thekaveman** [comment]
@lauriemerrell we're more than happy to help explore the new paradigm!

It does appear that [`save_to_gcs()` allows for a `bucket` param](https://github.com/cal-itp/calitp-py/blob/main/calitp/storage.py#L20) to override using `get_bucket()`; so we should be good with minimal changes, just using `is_development()` as mentioned.

**Comment by lauriemerrell** [comment]
Awesome, thank you! That's a great question re: docs... I actually think the main thing (not actually directly to related to this question about buckets) might just be adding a note in the datasets and tables section of the docs: https://docs.calitp.org/data-infra/datasets_and_tables/overview.html about what the Amplitude data is.
