### ISSUE TITLE
Hosted GTFS validator

### ISSUE THREAD

**Issue by e-lo** [cal-itp/data-infra#15]
**Source**: https://github.com/MobilityData/gtfs-validator

**Timing**: We want to wait for v2.0 (likely Jan/Feb), but want it to be spun up by the spring.

**Dependencies**: This is a dependency for the following 2021 MSD milestones:
1. 2021 Q2 Launch DIY GTFS Assessment Toolkit

**Priority**: Fairly high

**Interested Parties**: MSD Team @mcplanner @e-lo

**Comment by machow** [comment]
Working on this now, as part of #14. Going to try using a KubernetesPodOperator to run the validator. A big piece is making sure that it plays well in our dev environment. Otherwise, if getting the operator up takes more than a day or two, putting up a server and using the SSHOperator is a surprisingly robust solution (that can be replaced later with the right way :).

**Comment by machow** [comment]
Here are some notes on using the KubernetesPodOperator. The key challenge is getting google cloud credentials to work on dev, so that we can access the data in our buckets.

## Background

**Configuring to use secrets on local dev**

* Google cloud tutorial on [adding authentication secret to kubernetes](https://cloud.google.com/kubernetes-engine/docs/tutorials/authenticating-to-cloud-platform)
* Google composer tutorial on [mounting the secret in KubernetesPodOperator](https://cloud.google.com/composer/docs/how-to/using/using-kubernetes-pod-operator#secret-config)
* Astronomer.io on [running a pod operator locally](https://www.astronomer.io/docs/cloud/stable/develop/kubepodoperator-local)
* Source code of [GKEPodOperator](https://github.com/apache/airflow/blob/5786dcdc392f7a2649f398353a0beebef01c428e/airflow/contrib/operators/gcp_container_operator.py)

**Making sure the pod doesn't hog resources**

* [See this article](https://medium.com/grensesnittet/best-practises-for-kubernetespodoperator-in-cloud-composer-91760f848a39)

**Things that seem like a bad idea**

* Attempting to [mount a bucket](https://medium.com/grensesnittet/mounting-a-gcp-bucket-as-nfs-in-kubernetes-8f6d3faf4da3). Also see this [mailing list entry](https://groups.google.com/g/cloud-composer-discuss/c/gcoaUPSAn1k), where nobody seems to know how to do it.

## Solutions

I want to get a working prototype up by EOD, so may try having dev run pods in the production cluster (which is not running many tasks right now). This will let us skip putting secrets in when running on dev for now. While I'm working on loading tables into bigquery, maybe we can get a more kubernetes saavy person from jarvus to shore things up.

**Comment by machow** [comment]
Closing, since we're running https://github.com/cal-itp/gtfs-validator-api our pipeline!

**Comment by mcplanner** [comment]
Moving to Teamwork
