### ISSUE TITLE
Amplitude Benefits: Invalid timestamp causing DAG failure

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1542]
Starting on May 27, we have been seeing this error in the `amplitude_benefits.bigquery_to_views` DAG task: 

`google.api_core.exceptions.BadRequest: 400 Error while reading table: amplitude.benefits_events, error message: JSON parsing error in row starting at position 35112: Couldn't convert value to timestamp: Could not parse '2022:05:27 01:02:50.047099' as a timestamp. Required format is YYYY-MM-DD HH:MM[:SS[.SSSSSS]] or YYYY/MM/DD HH:MM[:SS[.SSSSSS]] Field: processed_time; Value: 2022:05:27 01:02:50.047099`

**Comment by angela-tran** [comment]
I queried the Amplitude Export API directly and found that `processed_time` there also contains colons. Therefore, the incorrect date format is coming from Amplitude itself.

I got a response from the Amplitude support team in this [Community post](https://community.amplitude.com/instrumentation-and-data-management-57/incorrect-date-format-for-processed-time-field-from-the-export-api-1089) that their Engineering team is aware of the issue and that "none of the existing broken/bad data can be fixed in the short term."

I think our best path forward is to add some code to our Airflow operator to fix the broken datetimes.

**Comment by angela-tran** [comment]
I spent some time today working on code in our operator to fix the improperly-formatted date values. Then I queried the Amplitude API to see what the various bad formats were, and I noticed values that previously were wrong are now in the right format 😑 

I'm now re-running the failed DAG runs in Composer.

**Comment by angela-tran** [comment]
### Before
![image](https://user-images.githubusercontent.com/25497886/184444268-c43fd078-07cf-413a-9d79-3b74cd37f5ef.png)

![image](https://user-images.githubusercontent.com/25497886/184444285-96bb9271-ec5a-4e37-8de8-5885d1af193b.png)

### Re-running
![image](https://user-images.githubusercontent.com/25497886/184444313-afe68d08-7253-4c5b-bdd9-5f42833c07da.png)

**Comment by angela-tran** [comment]
The 6 runs that are still failing are due to #1682.

Closing this ticket since invalid timestamps don't seem to be a problem anymore.
