### ISSUE TITLE
Hosted GTFS-Realtime Validator

### ISSUE THREAD

**Issue by e-lo** [cal-itp/data-infra#16]
**Source**: https://github.com/CUTR-at-USF/gtfs-realtime-validator
OR
https://github.com/interline-io/transitland-lib

**Timing**: Ready! By Spring!

**Dependencies**: This is a dependency for the following 2021 MSD milestones:
1. 2021 Q2 Launch DIY GTFS Assessment Toolkit

**Priority**: Fairly high

**Interested Parties**: MSD Team @mcplanner @e-lo

**Comment by e-lo** [comment]
@mcplanner - is there a substantive difference in the transitland-lib version?

**Comment by hunterowens** [comment]
Configuration Items needed, per @mcplanner 

- [ ] 20 second rather than 35 second Update Frequencies, per the GTFS-RT state guidelines 
- [ ] 100% (ish) uptime, running in the background on the state of CA gtfs-rt feeds
- [ ] store uptime results so that uptime statistics for feeds can be generated. 

very likely more TK

**Comment by mcplanner** [comment]
Closing as a duplicate.
