### ISSUE TITLE
Turn off/disable v1 pipeline for RT and schedule

### ISSUE THREAD

**Issue by atvaccaro** [cal-itp/data-infra#2109]
## Services tasks

- [x] Tear down `gtfsrt-v3` node pool
- [x] Delete `gtfsrt-v3` k8s yaml (https://github.com/cal-itp/data-infra/pull/2110)
- [x] Delete `gtfsrt-v3` application code (https://github.com/cal-itp/data-infra/pull/2110)

## Airflow tasks

- [x] Pause legacy RT parsing/validation DAG
- [x] Pause legacy Schedule download/validation DAG
- [x] Delete legacy parsing/validation DAGs (https://github.com/cal-itp/data-infra/pull/2111)
- [x] Delete legacy external table tasks (https://github.com/cal-itp/data-infra/pull/2111)

## dbt tasks

- [ ] ~Disable legacy RT source and downstream models~
- [ ] ~Disable legacy Schedule source and downstream nodes~

We are just going to disable rather than delete for now; this should preserve the docs but indicate the data is stale. We cannot do this until publishing at least is migrated, since disabling them will raise compilation errors if they are still used.

**Comment by lauriemerrell** [comment]
see also #1355

**Comment by lauriemerrell** [comment]
Priority here is to reduce costs by turning off *ingest*, not to fully turn off access to v1 data (because data consumer migrations are not yet complete). 

Order of operations:
1. Turn off things in non-code ways (i.e., pause Airflow DAGs etc.)
2. One PR per heading in issue description actually *deleting* associated code (i.e., *delete* Airflow DAGs)
3. BigQuery stuff (#1355 and potentially moving tables to new locations) can wait

**Comment by atvaccaro** [comment]
I think we can consider this done?! Everything is disabled/paused at this point.
