### ISSUE TITLE
User Story: daily schedule vs RT number and percent of trips

### ISSUE THREAD

**Issue by tiffanychu90** [cal-itp/data-infra#2236]
## User stories
---

### Summary

As an analyst, I want to see which scheduled trips have RT vehicle positions available for that day. If I am picking a date to do a deep-dive analysis, I want to select a day that has more RT data available.

### Table Schema
* Grain: `feed_key-name-route_id-service_date`
* Timeframe for table: 1 week in Dec 2022 (Dec 5-11)
* Identifier columns: `feed_key`, `name`, `service_date`, `route_id` + `route_short_name` or `route_long_name`
* Metric columns: `n_scheduled_trips`, `n_vp_trips`, `pct_vp = n_vp_trips / n_scheduled_trips`
* Notes:
   *  As is, if there is even 1 vehicle position available, it counts. 
   * Pending exploratory work: we will want to filter out RT trips not meeting a certain threshold (maybe just time threshold...at least 5 min of RT data)

### Tester [Stakeholder]

1. @tiffanychu90 

# Sprint Ready Checklist
1. - [ ] Acceptance criteria defined
2. - [ ] Team understands acceptance criteria
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria
4. - [ ] Acceptance criteria is verifiable / testable
5. - [ ] External / 3rd Party dependencies identified

**Comment by natam1** [comment]
Hi! I have a working draft of the v2 version of the rt_vs_sched table but do not have it set up as an incremental table yet. I think the v2 table meets the needs of this user story (just need to sort out some of the code still)

**Comment by lauriemerrell** [comment]
Thanks @natam1 ! Can you send me the table to look at / do you want help making it incremental?

**Comment by natam1** [comment]
Got a first run of the table syntax in my dbt staging:
cal-itp-data-infra-staging.natalie_mart_ad_hoc.fct_gtfs_scheduled_vs_vehicle_positions 
(not incremental yet or with the 5 positions on a day). I think the table doesn't actually have data now since it is taking the fct_vehicle_locations from my staging version

**Comment by lauriemerrell** [comment]
Thanks @natam1 ! I think this looks like a good initial table -- I think I would be able to assess more when I see the actual SQL to confirm the sources of all the data points. Otherwise a few stray thoughts:
* I think ideally we probably will want the schedule `feed_key` and schedule and VP `base64_url` values in addition to GTFS dataset key.
* This is probably a question for both you @natam1 and @tiffanychu90 -- how are we handling trip ID mismatches? So for example the issue we have had with at least one agency where the schedule and RT trip IDs do not align. It's possible you could have 100 schedule trip ID values on a given route and 100 RT trip ID values on the same route but none of them are the same. Do we want to have a separate number that captures percent of trip ID alignment?
* I wonder if we would also want some summary statistics like "scheduled first departure" and "actual first observation" or something, defer to you all on that.

**Comment by natam1** [comment]
oh shoot I thought the query was there so sorry! hoping to do a draft PR today and will link it here! 

In this table I am just counting the distinct trip IDs for each day and then matching the `fct_vehicle_locations` count with the `fct_daily_scheduled_trips` count. I think we were merging on `trip_id` on the first iteration in v1 and then moved to route. I do like the idea of including the trip id alignment!

**Comment by natam1** [comment]
https://github.com/cal-itp/data-infra/commit/78afec039b7a0f76694726f776479f8619a416ab first round of SQL!

**Comment by lauriemerrell** [comment]
@natam1 thank you! Broadly looks good I just left a few comments: https://github.com/cal-itp/data-infra/commit/78afec039b7a0f76694726f776479f8619a416ab

**Comment by tiffanychu90** [comment]
> * This is probably a question for both you @natam1 and @tiffanychu90 -- how are we handling trip ID mismatches? So for example the issue we have had with at least one agency where the schedule and RT trip IDs do not align. It's possible you could have 100 schedule trip ID values on a given route and 100 RT trip ID values on the same route but none of them are the same. Do we want to have a separate number that captures percent of trip ID alignment?

I like this `pct_trip_id_alignment` column, but it would probably be done with scheduled trip ID as the denominator? 100 RT trip IDs differing from the 100 scheduled trip IDs would have 0% alignment. I think that would be the directionality we want, since quite a few things are done off of schedule info.

> * I wonder if we would also want some summary statistics like "scheduled first departure" and "actual first observation" or something, defer to you all on that.

I wonder if this can be carved out as a separate table that is left at the trip-level. The above is aggregated to the route-level. Right now, how I'm thinking about this for segment speeds is that RT vehicle positions have to be attached to segments first, and from there, the first observation is captured. In the cases where the vehicle positions might be present while not traveling for a trip (pinging from a layover spot to the origin point) would get excluded, truncating timestamps too far in advance of the start of the trip.

**Comment by tiffanychu90** [comment]
Closing because #2413 makes significant progress how we pull trips from RT and scheduled
