### ISSUE TITLE
[reports site] Figure out how to select regional subfeeds in before the field was added in Airtable

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#2270]
For MTC 511 agencies on the reports site we want to only report on regional subfeeds, not the combined regional feed.

That logic is handled here: https://github.com/cal-itp/data-infra/blob/main/warehouse/models/intermediate/gtfs/gtfs_quality/int_gtfs_quality__daily_assessment_candidate_entities.sql#L101-L108, but this doesn't account for months before November 2022 when we hadn't yet entered the `regional_feed_type` field in Airtable so there is no formal way to select the subfeed over the combined feed. 

I think that this is resulting in months before December 2022 having a weird/buggy mixture of regional and subfeed data for MTC 511 agencies across all reports data elements (route & stop counts, service hours, validations, etc.). 

Depending on how @edasmalchi prioritizes this, we can potentially try to find other ways to impute this and/or suppress historical report generation for affected feeds. 

See the September 2022 report for ITP ID 10 (Altamont Corridor Express) for an affected feed

**Comment by edasmalchi** [comment]
Since the reports site is structured at the organization level, displaying service levels and route/stop counts from the MTC 511 regional feed on individual reports, as viewable [here](https://test--cal-itp-reports.netlify.app/gtfs_schedule/2022/09/10/index.html) (as of Feb 7), is confusing and we should **not** publish January reports as-is.

I would prefer to have more history than December for those feeds, but I'm also aware that we're already a week into February. My suggestion would be to investigate imputing this info, and if it's relatively easy to go ahead and do so. If there isn't time to investigate/fix before, say, next Wednesday, please go ahead and _suppress_ reports for affected months/agencies and we can publish January reports like that.

Thanks!

cc @holly-g, @o-ram

**Comment by lauriemerrell** [comment]
I will look at this first thing tomorrow

**Comment by edasmalchi** [comment]
thanks Laurie! reminder that I will be ooo the rest of this week
