### ISSUE TITLE
User Story: Add attributes to SBMTD Tap Data for Export

### ISSUE THREAD

**Issue by j-meelah** [cal-itp/data-infra#2342]
As a (SBMTD) payments metrics dashboard user, I would like bus number and a device ID columns added to the data available for export, so that I can more easily reconcile missing attributes from transaction data.

Notes:
Nice to have would be a “DayType” column. With a value of 1 for weekdays, 6 for Saturday, and 7 for Sunday.

# Sprint Ready Checklist
1. - [x] Acceptance criteria defined
2. - [x] Team understands acceptance criteria
3. - [x] Team has defined solution / steps to satisfy acceptance criteria
4. - [x] Acceptance criteria is verifiable / testable
5. - [x] External / 3rd Party dependencies identified

**Comment by charlie-costanzo** [comment]
@j-meelah two questions came up from this work:

> I would like bus number and a device ID columns added to the data available for export

I've added two columns to their export table, the first being `device_id`. But for the second column I had to guess that `vehicle_id` = `bus number`?

> Nice to have would be a “DayType” column. With a value of 1 for weekdays, 6 for Saturday, and 7 for Sunday.

I've added the `day_of_week` calculation to payments_rides in #2330, but as-is Bigquery provides: `values in the range [1,7] with Sunday as the first day of the week` 

Is it worth massaging the calculations to their specific ask, or leave it as-is since it actually provides a greater level of detail this way?
