### ISSUE TITLE
Investigate failing Sentry tests in payments pipeline 

### ISSUE THREAD

**Issue by charlie-costanzo** [cal-itp/data-infra#2592]
Description:
For certain tests in the payments pipeline identified as a result of https://github.com/cal-itp/data-infra/issues/2500, investigate the significance of their failures and whether the tests should exist in their current form

Tests to investigate:
* Tab 2 titled 'Investigate' in the tracking spreadsheet below
  * Rows 2-3

[Tracking Spreadsheet](https://docs.google.com/spreadsheets/d/16tNX56CgG2gXAMEQiVftFo3ldF3Ggn1TmwgcqSwTQjc/edit?usp=sharing)

Background:
* Rows 2-3 in the second tab called 'Investigate' 
  * `test_device_transaction_pairs_common_fields`
  * `validate_cleaned_device_transaction_pairs_common_fields`
* They're the same test, in different pipelines
* The tests are currently assessing differences among 7 columns between tap-on/tap-off transactions for the same ride that are expected to be the same

Questions:
* Are all of these fields important? Should we be concerned and follow up, or are some of them unnecessary?
* Is this the best format?
  * The information these tests represent may be better suited for a reliability dashboard instead of a Sentry alert

**Comment by SorenSpicknall** [comment]
@charlie-costanzo, I think this merits further investigation RE: assumptions we make about LittlePay data. I'm supportive of eliminating these tests for the moment and moving the representation over to a dashboard, because the tests seem to indicate an underlying misunderstanding we have about how customer IDs, device IDs, etc. are assigned.

Looking at the patterns of test violations we see here, I suspect that it's possible for a customer ID or device ID to change based on real-time payment factors (maybe somebody reloads a fare card and an ID changes?), and possible for the other fields to change based on real-time route factors (e.g. one route that turns into another route, or a vehicle ID that changes at a route turnaround point). Our current joins produce coherent tap-on, tap-off pairs aside from these violations that seem like they're probably explainable.

So I think we should take these tests out of service, do some factfinding in LittlePay documentation, then come back and reuse some of the old test code to produce new tests or a new dashboard if appropriate. Does that seem right?

**Comment by charlie-costanzo** [comment]
Hey @SorenSpicknall thanks for digging into this and writing this up, I think taking these tests out of service and going back to the Littlepay docs makes a lot of sense for now. Then we can re-implement however best based on what we find.
