### ISSUE TITLE
Investigate flaky hourly stop times parse job

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#2652]
Overnight (5/26/23) we [had another instance](https://o1d2fa0877cf3fb10p-tp.appspot.com/log?execution_date=2023-05-26T03%3A00%3A00%2B00%3A00&task_id=stop_times_txt&dag_id=unzip_and_validate_gtfs_schedule_hourly&map_index=-1) of a flake we've seen in the `unzip_and_validate_gtfs_schedule_hourly.stop_times_txt` job: 

```
Task exited with return code Negsignal.SIGKILL
```

We saw this multiple times during the hourly backfill. We should try to figure out why this task in particular is flaky. 

When this task fails, it requires a targeted re-run of the dbt warehouse job to pick up the missed data.

**Comment by atvaccaro** [comment]
This hasn't occurred since 2023-05-26; I'm tempted to close if it's quite for another week or so. I think the most likely solution would be to move the parsing to a PodOperator which would add a lot of not-useful tasks to the jobs node pool, increasing actual costs as well as the code overhead of an additional job image.
