### ISSUE TITLE
speedmap app tweaks

### ISSUE THREAD

**Issue by edasmalchi** [cal-itp/data-infra#2769]
## User story

As a [CA Transit Speed Maps](https://analysis.calitp.org/rt/README.html) user, I love the new maps! They'd just be a little easier to use with a few of these potential tweaks.

Issue created to document and assess feasibility with @atvaccaro, may not complete all

### App-side Tweaks

- [x] Title renders at 1000px width (better fit in JupyterBook width)
- [x] "Loading..." or something similar displayed in map during render wait (low priority)
- [x] Change map "default" centroid + zoom to full California extent
- [ ] Fix map on mobile? (need not be a first-class experience but currently not working at all -- reloads in a loop?)
- @edasmalchi to investigate further but new link might be enough?
- [ ] ~Automatically unzip .geojson.gz on download, so download returns plain .geojson (low priority/maybe impossible?)~
- [x] Tooltip label change in speedmap `type`: `(Stop name unavailable)` -> `Non-stop segment`
- [x] Custom tooltip style, new `type` for speed variation maps (to refine)
- [x] bit of transparency

### Analyst-side tweaks

- [x] round GTFS stop sequence (interpolated segments are otherwise long floats)
- [x] "view full map in new tab"
- [x] add stop name, stop_id, route_id to variation for display, use new `speed_variation` type

### Acceptance Criteria

TBD

**Comment by atvaccaro** [comment]
I have a [commit](https://github.com/cal-itp/data-infra/commit/c50b0d8c454679d6541260599c4a5a44a4a38eaf) and a [PR](https://github.com/cal-itp/data-infra/pull/2772) and I'll check things off as I complete them!

I think a couple of these are trickier than they may be worth.

> * [ ]  "Loading..." or something similar displayed in map during render wait (low priority)

This is going to be tricky because we're loading multiple layers asynchronously. I added a basic spinner that relies on pre-existing data load events (even for tiles), so there's at least a bit of feedback, but I don't think it's really what you were imagining (i.e. a spinner while loading _our_ data specifically).

> * [ ]  Fix map on mobile? (need not be a first-class experience but currently not working at all -- reloads in a loop?)

I was able to get [this](https://leaflet-speedmaps--cal-itp-data-analyses.netlify.app/?state=H4sIAKJdbmQC_6WSX2vbMBTFv4rww54SuVk2uv5ZIWsLGzRNWQyFpcVc26qjVdYVunIdx_i7T3KyZQxKH_ZgzNU9Ovf8rt1FGioRnTJdKzVikYJWWPL1qvvdia6O2dKBE-yrLNcNtOxWuAbtc-T1tVVBsnbO0Gkck0MLpeAlYqkEGEk8xyrOQUlnxhWYsZNKUFwcp7TWvBT4k9C_t8ELNKiWJO3T9CN2yHAzY3PhLLIvNbGlEaJgczDEZnN2J-B_olTBNoUqTa6XSZosFjfJt7v09vr-jXSPw7ZcqlAf1rdFrA5VluEmrHI1_cAnIzaeTD7xj_7eajrlJ_v66DEYZUDCR0pz1E-y9He6f3E66vle5UHAOswLPRBZICfsDuYFW89s427bx93GP23f2Z4bXQYENE6ipsEenLMyq8NBGPMuR9OesXNgayuePj_8mds0DUcjNDkrhPPTOdoyDmrr_wb3EF0sfHc5dP0XOY_hgnmKnTlaYq86DxADwV9ZyBtezr4ni2AUMlOdFViBHGJHkOVFOK1g82O36vdHvnwBK0G7oCjAPqegVNT3_S9c7sNd3QIAAA%3D%3D) to load on my phone; do you want to test with a couple different devices synchronously?

> * [ ]  Automatically unzip .geojson.gz on download, so download returns plain .geojson (low priority/maybe impossible?)

Currently the download link references the actual HTTPS endpoint of the file in GCS, but I think there's two ways we could do this. I don't love either of them.

1. Add a parameter to the State that would allow you to specify a non-gzipped file to download; that would mean saving both a GeoJSON and gzipped-GeoJSON to GCS but has the advantage of avoiding any client-side work.
2. Perform the download operation via Javascript, which basically consists of fetching the file, creating a fake link with the blob content in the DOM, and "clicking" the link via Javascript. This would avoid storing additional files in GCS but it may perform poorly on large files (10s of MB).

**Comment by atvaccaro** [comment]
>  Custom tooltip style, new type for speed variation maps (to refine)

For this, do you have a list of fields? We could re-use the same basic styling with additional fields or create something from scratch.

**Comment by edasmalchi** [comment]
> This is going to be tricky because we're loading multiple layers asynchronously. I added a basic spinner that relies on pre-existing data load events (even for tiles), so there's at least a bit of feedback, but I don't think it's really what you were imagining (i.e. a spinner while loading our data specifically).

Sounds good, let's see what the spinner looks like but this isn't essential.

> Currently the download link references the actual HTTPS endpoint of the file in GCS, but I think there's two ways we could do this. I don't love either of them.

Yeah I figured, we'll just keep it as-is

> > Custom tooltip style, new type for speed variation maps (to refine)

> For this, do you have a list of fields? We could re-use the same basic styling with additional fields or create something from scratch.

Yeah, I'll get it to you in a bit. We might be able to do some interesting visuals since we have the p20, p50, p80 speeds and p80/p20, can talk more synchronously and/or I can do a mockup

The "opacity" param doesn't quite yield the desired effect, I think we might need to crack back open the color-handling code in the app.

So let's find time for a synchronous session to:

- look at the spinner
- debug mobile?
- brainstorm variation tooltip
- refine color handling to get (a bit) of transparency

**Comment by edasmalchi** [comment]
oh and I was able to load your link to the app itself on mobile too, but I haven't been able to get them to load on the published speedmap site. Maybe something about the iframe/JupyterBook interaction?

for example this doesn't work for me on iOS/Firefox: https://analysis.calitp.org/rt/district_07-los-angeles/13__speedmaps__district_07-los-angeles__itp_id_182.html

**Comment by atvaccaro** [comment]
![Screenshot_20230627-121519.png](https://github.com/cal-itp/data-infra/assets/4305366/18d127fd-63bd-4433-91a5-2d756c1366c2)

Ok I did just test on Chrome on my Pixel and it mostly works... What about Safari?

**Comment by atvaccaro** [comment]
I'll send a calendar invite!

**Comment by edasmalchi** [comment]
negative on Safari
![File](https://github.com/cal-itp/data-infra/assets/54728455/70b3ff88-1809-4c27-909e-387e618d08c3)

**Comment by atvaccaro** [comment]
glad that both of us hit the same high-resolution-screenshots-are-massive-images problem 😂

**Comment by edasmalchi** [comment]
It actually loaded in Safari on my work phone (same iOS major version)

But... that phone is bigger (13 Pro vs my 13 Mini) -- perhaps implies some sort of screen size issue??

**Comment by edasmalchi** [comment]
@atvaccaro finally rebuilt the site and it looks great!

Realized we don't quite have a mobile fix -- the view map in new tab is a good idea on its own, but since the page doesn't load properly in the first place I don't get a chance to click it! Will try to see if I can get a console/error messages out at some point

**Comment by atvaccaro** [comment]
> Realized we don't quite have a mobile fix -- the view map in new tab is a good idea on its own, but since the page doesn't load properly in the first place I don't get a chance to click it! Will try to see if I can get a console/error messages out at some point

Ah right... let me know if you find out anything. I'll ask around and see if anyone has a iPhone/iPad they'd be willing to let us test with.
