### ISSUE TITLE
Investigate Google Cloud deprecation of Container Registry in favor of Artifact Registry

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-infra#3369]
## User story / feature request

Determine what may be needed given [Google Cloud transition to Artifact Registry](https://cloud.google.com/blog/products/application-development/understanding-artifact-registry-vs-container-registry).

1. What's the end of life date?
2. What's the impact?
3. What's the level of effort?

### Acceptance Criteria

We're able to still publish containers?

**Comment by HaroldBooker** [comment]
Currently publishing to Github not google cloud container registry

**Comment by themightychris** [comment]
I found one `gcr.io` image [referenced within the repository](https://github.com/search?q=repo%3Acal-itp%2Fdata-infra+gcr.io&type=code):  `gcr.io/cal-itp-data-infra/dbt-spark:2023.3.28`

It's not clear to me whether this is actually being used by anything currently though.

There are 4 images listed in the Container Registry UI right now:

<img width="544" alt="Screenshot 2024-09-24 at 5 28 21 PM" src="https://github.com/user-attachments/assets/6793c82f-e03e-45fc-83b4-a70dca52acba">

The two `gtfs-archive` haven't had new versions pushed since early 2022 and we definitely build and host current versions of the archiver on GitHub's container registry

The `dbt-spark` one though as referenced above was last updated March 2023. I'm guessing that's for executing dbt Python models, which I recall Andrew/Laurie doing a demo of but do we have any Python models actually operationalized @charlie-costanzo ? I haven't been able to track down in the docs or data-infra repo where that `dbt-spark` image might have been built from.

We could certainly just pull the image down and push it back up to ghcr.io somewhere and update the references just to be safe, but ideally we can locate the source for this image and set up a build workflow for it

**Comment by themightychris** [comment]
That `dbt-spark` image is built from https://github.com/cal-itp/data-infra/blob/main/warehouse/Dockerfile.spark

**Comment by themightychris** [comment]
The [example Python model](https://github.com/cal-itp/data-infra/commit/892f2f11f1e2bc6e890f37c53530019b6ea06884) wasn't merged into the repository in that PR and only lives on in that PR's description. There are no active Python models in the warehouse currently.

@evansiroky do we want to put work into maintaining the ability to deploy Python models? A quick and dirty hack would be to just pull the existing image down from `gcr.io` and push it up under `ghcr.io` somewhere and update the references. Some additional work we might want to do though if we care about maintaining this capability:

- Set up a GitHub Action for automatically building and publishing this container image (low effort—unless we hit dependency issues building the image today)
- Put the example model somewhere longer-lasting than a PR description, like in a docs page on Python models
- Test it out again and make sure it still works as documented
