### ISSUE TITLE
NTD Ingestion – Remaining Tables in Dataset

### ISSUE THREAD

**Issue by charlie-costanzo** [cal-itp/data-infra#3403]
## User story / feature request

Part of #3401 

As a data engineer, I would like to ingest the data in the form of gcs blob storage and external tables for the remaining tables in the NTD dataset, extending the work found in `scrape_ntd.py` and `annual_database_service.yml` (found below).

Building upon the work completed in #3345

Existing NTD patterns:
- [script/scrape_ntd.py](https://github.com/cal-itp/data-infra/blob/main/script/scrape_ntd.py)
- [airflow/dags/create_external_tables/ntd_data_products/annual_database_service.yml](https://github.com/cal-itp/data-infra/blob/main/airflow/dags/create_external_tables/ntd_data_products/annual_database_service.yml)

General Cal-ITP Pipeline Patterns
- [Data Pipelines Documentation](https://docs.calitp.org/data-infra/architecture/data.html#data-pipelines)
  - [Adding a New Data Source](https://docs.calitp.org/data-infra/architecture/data.html#adding-a-new-data-source)
  - [Previous PR Patterns](https://github.com/cal-itp/data-infra/pull/2376)

### Acceptance Criteria

I can successfully access the data for the following tables from the https://www.transit.dot.gov/ntd/data-product website in the warehouse as external tables:
- Assets
- Expenses
- Fares/Funding
- Resources
- Security and Safety
- Service (previous years)

### Notes
---

**Comment by erikamov** [comment]
External tables on branch [3403-ntd-api-external-tables](https://github.com/cal-itp/data-infra/compare/3403-ntd-api-external-tables)

**Comment by erikamov** [comment]
* [External tables for 2022 API data](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1scal-itp-data-infra-staging!2sexternal_ntd__annual_reporting) were tested and working. I am still reviewing field types for each column, but could be deployed as is now (using default STRING) and as we work on modeling we can keep changing types as needed. 
 
* `historical__major_safety_events` and `historical__nonmajor_safety_and_security_events` external tables for Historical API data are failing because of the column names `:@computed_region_8fe2_rd7y` and `:@computed_region_m2nu_4dib`.
 @charlie-costanzo @mjumbewu  have you seen this problem before?

    The full error:
   `google.api_core.exceptions.BadRequest: 400 Error while reading table: cal-itp-data-infra-staging.external_ntd__annual_reporting.historical__major_safety_events, error message: JSON parsing error in row starting at position 0: JSON object specified for non-record field: latlon File: gs://calitp-ntd-api-products/major_safety_events/historical/dt=2024-09-18/execution_ts=2024-09-18T21:46:57.651684+00:00/historical__major_safety_events.jsonl.gz`

* The external tables for `XLSX Complete Monthly Ridership with Adjustments and Estimates Data` are also failing, but I think it is just my local configuration to access the XLSX files/buckets.

**Comment by erikamov** [comment]
I created the a PR with only the 2022 external tables https://github.com/cal-itp/data-infra/pull/3465 and will keep working on the XLSX tables to be deploy.

**Comment by erikamov** [comment]
2022 External Tables were successfully created on `cal-itp-data-infra.external_ntd__annual_reporting`.

New [PR created](https://github.com/cal-itp/data-infra/pull/3470) for NTD external tables for Complete Monthly Ridership with Adjustments and Estimates Data.

The remaining tables will not be created for now. If there is a need for those I kept the work on a [branch](https://github.com/cal-itp/data-infra/compare/3403-ntd-xlsx-safety-security-events-external-tables/). Those table will need some extra work to be created due to position of the column names and invalid characters on the name (see previous comments).

**Comment by erikamov** [comment]
Last PR merged. Next time the `create_external_tables` runs it will create those tables.

**Comment by erikamov** [comment]
Tables created and new fields will be added on the next `create_external_tables` DAG runs.

**Comment by erikamov** [comment]
DAG updated all tables successfully.
