### ISSUE TITLE
NTD Modeling – Staging and Intermediate – Remaining Tables in Dataset

### ISSUE THREAD

**Issue by charlie-costanzo** [cal-itp/data-infra#3404]
## User story / feature request

Part of #3401 

As a data engineer, I would like to make the remaining tables in the NTD dataset available as staging tables (and intermediate, as necessary), extending the work found in `warehouse/models/staging/ntd` (found below).

Building upon the work completed in #3345

Existing patterns:
- [warehouse/models/staging/ntd](https://github.com/cal-itp/data-infra/tree/main/warehouse/models/staging/ntd)

### Acceptance Criteria

I can successfully access the data for the following tables in the warehouse as staging and intermediate tables:
- Assets
- Expenses
- Fares/Funding
- Resources
- Security and Safety
- Service (previous years)

### Notes
---

**Comment by erikamov** [comment]
To help with the correct creation of the staging tables I created a [branch](https://github.com/cal-itp/data-infra/compare/3404-ntd-fix-type) to review the column types based on the [documentation](https://docs.google.com/document/d/1fWAQHj_FGPU8VrneIFaJfxP9H810a2mDziFLuk4FqN0/edit?usp=sharing) of each end point.
Also adding some optional columns that wasn't added because it wasn't part of the first json record.
