### ISSUE TITLE
Bug: duplicate entries showing up in the fct_transit_data_quality_issues table

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-infra#3407]
**Describe the bug**

I believe that the `fct_transit_data_quality_issues ` table should only ever have one entry per Airtable record. However, there are times when multiple records are showing up in the `fct_transit_data_quality_issues` table. This appears to happen whenever there is a change in either the GTFS Dataset or Service associated with the Airtable issue.

**To Reproduce**

See metabase question: https://dashboards.calitp.org/question/2516-fct-transit-data-quality-issues-with-duplicate-entries

**Expected behavior**

Each Airtable record should show up once.

**Additional context**

This is causing incorrect statistics to show up in the [Transit Data Quality Issue Dashboard](https://dashboards.calitp.org/dashboard/170-transit-data-quality-issue-dashboard).

**Comment by vevetron** [comment]
I think the issue is actually because an issue an airtable can have multiple gtfs records (or services) attached to it.
e.g. 
transit issue 1
<img width="521" alt="image" src="https://github.com/user-attachments/assets/a79180a6-a91a-4806-a2cc-fb4fd2dfe934">
has 5 duplicates but also 5 gtfs records attached to it.

2 of sets of duplicates are due to having multiple services attached to it.  It could also be because of issue_type but i'm not seeing that happening because airtable restricts you to only one issue type.

This happens during the unnest step in this [table](https://dbt-docs.calitp.org/#!/model/model.calitp_warehouse.int_transit_database__transit_data_quality_issues#depends_on
).

Solutions:
1. I don't think need all the different gtfs_source_ids or services, for the final table, and perhaps we can just pick the first one and do the joins on that.
2. We could just smash the duplicates later and make the unique field a list of the different entries.
3. (less desired) Stop airtable from allowing multiple services or gtfs feeds at the source.  Clean up the existing ones.

I think 2. is probably best if possible.

**Comment by vevetron** [comment]
In a call @evansiroky said choice 1 is fine.
