### ISSUE TITLE
Bug:  Data Pipeline failing on invalid service alerts value

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-infra#3498]
**Describe the bug**

Two tables (`fct_daily_service_alerts_message_age_summary ` and `fct_service_alerts_messages_unnested`) are failing because there is probably a GTFS-RT feed that put a string value in a field meant to be an integer value.

**To Reproduce**

[See failed Airflow job](https://b2062ffca77d44a28b4e05f8f5bf4996-dot-us-west2.composer.googleusercontent.com/dags/transform_warehouse/grid?root=&dag_run_id=scheduled__2024-10-12T14%3A00%3A00%2B00%3A00&task_id=dbt_run_and_upload_artifacts).

**Expected behavior**

The pipeline is able to gracefully reject service alert messages that have a string value where there should be an integer value.

**Additional context**

Additional fault-tolerance could be considered for invalid GTFS-RT files, but mainly working around this issue is important.

**Comment by vevetron** [comment]
This is one of the bad error messages:
`{"header": {"gtfsRealtimeVersion": "1.0", "incrementality": "FULL_DATASET", "timestamp": "1728446401"}, "metadata": {"extract_ts": "2024-10-09T04:00:00+00:00", "extract_config": {"extracted_at": "2024-10-09T02:00:26.520959+00:00", "name": "Bay Area 511 Santa Clara Transit Alerts", "url": "https://api.511.org/transit/servicealerts?agency=SC", "feed_type": "service_alerts", "schedule_url_for_validation": "https://api.511.org/transit/datafeeds?operator_id=SC", "auth_query_params": {"api_key": "MTC_511_API_KEY"}, "auth_headers": {}, "computed": false}}, "id": "SC_RTA:14647282", "alert": {"activePeriod": [{"start": "18446744011787391616", "end": "1728629940"}], "informedEntity": [{"agencyId": "SC", "routeId": "59"}, {"agencyId": "SC", "routeId": "ACE Yellow"}, {"agencyId": "SC", "routeId": "20"}, {"agencyId": "SC", "stopId": "61932"}], "cause": "CONSTRUCTION", "effect": "STOP_MOVED", "headerText": {"translation": [{"text": "Routes 20, 59, & Yellow ACE Shuttle: Temporary Bus Stop Closure at Mission College & Freedom (10/7/24 - 10/10/24)", "language": "en"}]}, "descriptionText": {"translation": [{"text": "Due to construction, the stop at Mission College & Freedom (RTI: 61932) will be closed between 10/7/24 - 10/10/24.\r\n\r\nTemporary Bus Stop Location: Mission College & Great America", "language": "en"}]}, "severityLevel": "WARNING"}}
`
Instead of having a normal timestamp for start like 1728629940 they have a crazy high number like 18446744011787391616.  Some part of the code is having trouble parsing the giant number.

**Comment by vevetron** [comment]
This recreates the bug:
```
SELECT distinct(alert.activePeriod) FROM `cal-itp-data-infra.external_gtfs_rt_v2.service_alerts` 
WHERE dt = '2024-10-09'
AND
hour = '2024-10-09T04:00:00+00:00'
AND base64_url = 'aHR0cHM6Ly9hcGkuNTExLm9yZy90cmFuc2l0L3NlcnZpY2VhbGVydHM_YWdlbmN5PVND'
LIMIT 10
```
`Error while reading table: cal-itp-data-infra.external_gtfs_rt_v2.service_alerts, error message: JSON parsing error in row starting at position 19710: Could not convert value 'string_value: "18446744011787391616"' to integer. Field: start; Value: 18446744011787391616 File: gs://calitp-gtfs-rt-parsed/service_alerts/dt=2024-10-09/hour=2024-10-09T04:00:00+00:00/base64_url=aHR0cHM6Ly9hcGkuNTExLm9yZy90cmFuc2l0L3NlcnZpY2VhbGVydHM_YWdlbmN5PVND/service_alerts.jsonl.gz`
