### ISSUE TITLE
Payments Research:  How much rider adoption

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#359]
## Goal(s)

* Program adoption for open loop payments

## Questions

* Are riders using new open loop payment option?
* How many compared to existing payment options?

## Metric

Trips by line as shown by "farebox" type (existing/new validators) (DAILY) 

## Data Source

Label which sources we have, which ones we need (when will we have them by?)

## View

_The table of data we'll create in the warehouse_

**Comment by mjumbewu** [comment]
@hunterowens How can we get access to fare box information from MST? Do they publish it in a machine readable format on a regular basis? This question is relevant to the following issues as well:
* https://github.com/cal-itp/data-infra/issues/370
* https://github.com/cal-itp/data-infra/issues/371
* https://github.com/cal-itp/data-infra/issues/372

Also, thinking forward beyond MST, will this fare box data be available from many of the CA transit agencies? This question comes up because most of the metrics that have been chosen for payments so far are comparative. In the event that a transit agency does not have their fare box data available in a useable format, are these metrics still valuable if they only include the Littlepay side of the information?
