### ISSUE TITLE
Analysts Can Quickly Query GTFS Schedule Data

### ISSUE THREAD

**Issue by charlie-costanzo** [cal-itp/data-infra#447]
Analysts currently have a number of tools available to them to query the data. However, due to a lack of data documentation, they'll likely have a difficult time navigating and understanding the data warehouse. 

Problems:
- To date, we have limited written information available to analysts supporting the data warehouse and the full breadth of our tools

Solutions:
- Tutorial format can be built upon to address basic queries and typical tables and columns used

Create issues from:
- Pieces needing research
- Solutions to implement

**Comment by machow** [comment]
Declaring bankruptcy on this--since this is a issue I put up when @charlie-costanzo was still getting a feel for things. He's stubbing out epics for the parts of the docs that should tackle this (see https://github.com/cal-itp/data-infra/issues/690).

* https://github.com/cal-itp/data-infra/issues/235
* create a table detailing when feeds in gtfs_schedule latest were extracted: https://github.com/cal-itp/data-infra/issues/708
* document explaining concept of fact and dimension tables: https://github.com/cal-itp/data-infra/issues/709
