### ISSUE TITLE
GTFS Guidelines: Existence of Pathways data for all child/parent stop relationships

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-infra#562]
## Question

Is there sufficient pathways data for all stops described using the child/parent stop relationship?

See related issue: cal-itp/data-analyses#165 

## Metrics

An MVP analysis of this would be to check up to three things:

1. Is at least one row in the stops table with a non-empty value in the field `parent_station`. If no, pathway data does not need to exist.
2. If Yes to answer 1, is there at least one row of data in the pathways table?

A more rigorous analysis of this issue would check to see if all child stops within a parent station can reach every other child stop within a parent station by traversing the defined pathways when simulating travel as an able-bodied person.

## Data sources

* stops table
* pathways table

## (Data Servicess Team to Copy and Fill Out Below)

The QuVR MD template below will be filled out by a member of the data services team.
This allows us to describe the request, in a way that is easy to hand-off for analysis.
After the research phase, we will sync with the asker to figure out if the metric and dashboard pieces are needed.

Before starting research:

* **Question**: Question written as a single sentence.
* **View**: E.g. `views.gtfs_schedule_fact_daily_feed_files`.
* **Research**:
  - How should the results be presented?
  - When are they needed by?

After reviewing research with the asker:

* **Metric**: what specific calculations are needed?
* **Dashboard**: where should we put the result?

**Comment by evansiroky** [comment]
Blocked until #615 is resolved.

**Comment by owades** [comment]
Since gtfs-validator checks pathways for errors such as [pathway_to_platform_with_boarding_areas](https://github.com/MobilityData/gtfs-validator/blob/master/RULES.md#pathway_to_platform_with_boarding_areas), [pathway_to_wrong_location_type](https://github.com/MobilityData/gtfs-validator/blob/master/RULES.md#pathway_to_wrong_location_type), and [pathway_unreachable_location](https://github.com/MobilityData/gtfs-validator/blob/master/RULES.md#pathway_unreachable_location), I think Evan's MVP logic described above would be sufficiently thorough. The validator would validate those pathways, and so we would just check for the related errors.
