### ISSUE TITLE
Refine CODEOWNERS

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#663]
It sounds like having a `*` means you get added to every review. Can we tune down to minimize the number of PRs people are added on?

* someone to research how CODEOWNERS works
* adjust to not have e.g. @themightychris on every PR

**Comment by lottspot** [comment]
having a `*` means you get added to every review _not already covered by another rule_. The ideal way to handle this IMO would be to have more owners (e.g., set a fallthrough owner for the entire `/airflow` path) rather than eliminating the top level owners (i.e., `*`). From the [example codeowners file](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#example-of-a-codeowners-file) (emphasis mine):

> These owners will be the default owners for everything in the repo. **Unless a later match takes precedence**, @global-owner1 and @global-owner2 will be requested for review when someone opens a pull request.

For a real-life example of this behavior in action, check out #649 where Charlie was added as a reviewer automatically (as seen by the "Nkdiaz requested a review from charlie-costanzo as a code owner" event) but none of the reviewers from `*` were added in that fashion.
