### ISSUE TITLE
Migrate to gtfs validator v3.1.0+

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#685]
## User Story

As a transit data quality analyst, 
I want to be using at least version 3.1.0 of Mobility Data's GTFS validator,
so that I can be using the most up-to-date version of the validator with all of its checks
and so that the validator can be generating HTML reports of validation results

## Acceptance Criteria

Given each new feed version that is identified after downloading,
When the nightly pipeline runs various GTFS Schedule validation tasks,
Then the JSON output should be ingested and be able to be read in the same manner within the [Critical Validation Errors metabase question](https://dashboards.calitp.org/question/142-critical-validation-errors),
And the HTML output should be saved within our google cloud storage for potential later use to display to transit agencies

- [ ] Validator version is tracked in the validation outputs so that future upgrades will be easier

### Caveats

A backfill of previous data is not expected in order for the acceptance criteria to be fulfilled.

**Comment by isabelle-dr** [comment]
Hi @machow!
The validator is still in pre-release because we still need [this PR](https://github.com/MobilityData/gtfs-validator/pull/848) to be merged, but it can be used to get the latest rules we added. This last PR won't have any effect on them. 

You can use the documentation from [here](https://github.com/MobilityData/gtfs-validator/blob/docs/v3.0.0/docs/USAGE.md) if you'd like to go ahead and use it!

We added the option to export the notice schema as a json file :)

Let us know if you have any questions!

**Comment by machow** [comment]
Hey, sorry for the late reply--thanks for the handy info, and option to dump the schema to json!

**Comment by evansiroky** [comment]
Just updated the title to request updating to at least v3.0.1 to bring in some updates that have more nuance around `shape_dist_traveled` values.

**Comment by isabelle-dr** [comment]
Hello! 
I received a notification because I left a comment in this thread. :)
For what it's worth, we are releasing 3.1.0 this week. In this release, the validator will output an HTML file in addition to the JSON report, and this file will have the validator version mentioned on it. 
The JSON report will remain unchanged for now: the validator version won't appear on it.

**Comment by evansiroky** [comment]
Updated issue description and bumped up requested version to 3.1.0.

**Comment by lauriemerrell** [comment]
Reassigning to @atvaccaro based on discussion -- we will do this as part of the GTFS schedule rewrite.
