### ISSUE TITLE
Backfill 'Route Z, Stop A' on MST (and SacRT)

### ISSUE THREAD

**Issue by jenro1** [cal-itp/data-infra#688]
## Question

Can we find a way to backfill the 'Route Z, Stop A' transactions on MST (first) and SacRT (second) in the same way that we did for SBMTD?

## Metrics

I believe this will rely on using the lat/long information to identify stops and then seeing if that stop is exclusive to one route, or is served by more than route

## Data sources

MST and SacRT ridership

## Timescales/other information

I have put a request out to SC Soft (the device vendor) to better understand why some transactions do not have a route or stop defined. Will update when I have more. If it's possible to get a sense of how many stops are exclusive to one route, that would be a helpful first step in understanding whether this exercise will be fruitful!

**Comment by mjumbewu** [comment]
I'm going to deprioritize this for right now while we wait to hear whether MST has data that will make route reconciliation easier. For example, **if MST (and SacRT) can verify that the vehicle IDs match what would be in the GTFS real-time data, then we can match with vehicles and determine the route from there**.

Baring that, for SacRT, the lift may not be very high, because
1. they have relatively few lines to begin with, and
2. only about 1/6th of the `Route Z` records have `Stop A` as the location name (the rest have what seems to be accurate stop info). So, if we can see which routes correspond to the actual stops, we should be able to reconcile many of the other 5/6ths of the trips.

For MST, all of the `Route Z` records have `Stop A` as the location name, so all we have to go on is guessing which stop it is based on the longitude/latitude. Also, there are many more routes, so a much higher chance that those stops are served by multiple routes.
