### ISSUE TITLE
Estimate cost of running airflow v2

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#745]
Currently we run airflow v1, which provisions a kubernetes cluster with 3 instances. The new model prices by compute, storage, and memory usage. Can we get a monthly estimate for cost (e.g. how much would it have cost to run last month?)

**Comment by lottspot** [comment]
A "small" (0.5 vCPU, 1.875 GB mem/worker) composer v2 environment most closely models the memory demand of our current composer components, which all request 1 GB of memory or less. Upsizing to a "medium" (2 vCPU, 7.5 GB mem/worker) environment may be necessary if the CPU capacity of the "small" environment proves inadequate (some components can be seen requesting up to 1 vCPU).

The SKUs as they would apply to a "small" v2 environment:

| item | approximate quantity |
| --- | --- |
| compute CPUs | 2.5 |
| compute memory | 9.4 GB |
| compute storage | 5 GB |
| db storage | ? (assume 10GB) |
| environment fee | small |

Based on the [pricing table](https://cloud.google.com/composer/pricing) this utilization would model the following approximate cost for 744 hours of utilization (31 days) in the us-west2 region:

| item | approximate cost |
| --- | --- |
| compute CPUs | $100.44 |
| compute memory | $41.96  |
| compute storage | $0.75  |
| db storage | $1488  |
| environment fee | $312.48 |
| **total** | **1943.63** |

This is likely to be a somewhat pessimistic estimate due to the following factors:

* database size, which is the most expensive cost component, is an unknown.
* Composer v2 performs autoscaling of workers, scaling down to 1 during idle time (estimate based on 3 fully active workers).

**Comment by machow** [comment]
@lottspot is db storage missing a decimal? (should it be 14.88?). I think around $500 a month as a pessimistic estimate makes sense. 

However, I'm starting to realize that there are two factors:

* composer v2
* airflow v2 (which can run on composer 1 or 2.....)

It looks like composer v2 maybe does not give us much control over how much memory workers have? We have some processes that take a fair amount of memory. I wonder if it might be better for us to upgrade to composer **v1** and airflow v2... this would let us basically keep running with the same cost structure, but use a version with longer term support by gcs and nice features......

**Comment by lottspot** [comment]
Yeah, that DB storage estimate was _wildly_ off.... I calculated GB/hrs instead of GB/mo, which is how it is charged. I've edited it to fix the number.

**Comment by lottspot** [comment]
Estimates for medium and large environments:

Medium (scheduler: 2 vCPUs, 7.5 GB x 2; webserver: 2 vCPU, 7.5 GB x 1; workers: 2 vCPUs, 7.5 GB x 2-6)

sku | quant | unit cost | month cost
-- | -- | -- | --
Compute CPUs | 18 | 0.972 | 723.168
Compute Memory | 67.5 | 0.405 | 301.32
Compute Storage | 45 | 0.009 | 6.696
Database Storage | 10 | 2 | 2
Medium Env | 1 | 0.66 | 491.04
**total** |   |   | **1524.224**

Large (scheduler: 4 vCPUs, 15 GB x 3; webserver: 2 vCPU, 7.5 GB x 1; workers: 4 vCPUs, 15 GB x 3-12)

sku | quant | unit cost | month cost
-- | -- | -- | --
Compute CPUs | 64 | 3.456 | 2571.264
Compute Memory | 232.5 | 1.395 | 1037.88
Compute Storage | 160 | 0.032 | 23.808
Database Storage | 10 | 2 | 2
Large Env | 1 | 1.02 | 1.02
**total** |   |   | **3635.972**

It's worth noting that the larger the environment gets, the more pessimistic these estimates become due to the fact that they are calculated based on the maximum number of workers running for the entire month.

**Comment by lottspot** [comment]
Below are optimistic estimates (assuming the minimum scale of workers running at all tims) for all environment sizes. The actual cost is likely to fall somewhere in between the optimistic and the pessimistic estimates.

Small (scheduler: 0.5 vCPUs, 1.875 GB x 1; webserver: 0.5 vCPU, 1.875 GB x 1; workers: 0.5 vCPUs, 1.875 GB x 1)

sku | quant | unit cost | month cost
-- | -- | -- | --
Compute CPUs | 1.5 | 0.081 | 60.264
Compute Memory | 5.625 | 0.03375 | 25.11
Compute Storage | 3 | 0.0006 | 0.4464
Database Storage | 10 | 2 | 2
Small Env | 1 | 0.42 | 312.48
total |   |   | 400.3004

Medium (scheduler: 2 vCPUs, 7.5 GB x 2; webserver: 2 vCPU, 7.5 GB x 1; workers: 2 vCPUs, 7.5 GB x 2):

sku | quant | unit cost | month cost
-- | -- | -- | --
Compute CPUs | 10 | 0.54 | 401.76
Compute Memory | 37.5 | 0.225 | 167.4
Compute Storage | 25 | 0.005 | 3.72
Database Storage | 10 | 2 | 2
Medium Env | 1 | 0.66 | 491.04
total |   |   | 1065.92

Large (scheduler: 4 vCPUs, 15 GB x 3; webserver: 2 vCPU, 7.5 GB x 1; workers: 4 vCPUs, 15 GB x 3)

sku | quant | unit cost | month cost
-- | -- | -- | --
Compute CPUs | 26 | 1.404 | 1044.576
Compute Memory | 97.5 | 0.585 | 435.24
Compute Storage | 70 | 0.014 | 10.416
Database Storage | 10 | 2 | 2
Large Env | 1 | 1.02 | 1.02
total |   |   | 1493.252

**Comment by lottspot** [comment]
I believe we can also select custom sizing for our workers, so we may be able to, for example, utilize scheduler/webserver sizes from the small environment, but select larger worker sizes.

**Comment by lottspot** [comment]
The decision has been made to stick with composer v1 for the airflow2 upgrade
