### ISSUE TITLE
GTFS Reports

### ISSUE THREAD

**Issue by hunterowens** [cal-itp/data-infra#75]
I suspect this is gonna become several issues, but as discussed on the Monday call, we'd like to generate a monthly "GTFS" report, capturing elements we can automate from the grading schema and either post on the web or generate PDFs to email or both. @mcplanner is working (tracking in teamwork) what the the report will look like, but let's have  astub here for discussion

**Comment by mcplanner** [comment]
Draft monthly report
<https://docs.google.com/document/d/1-iXNdl4f2EbYayKg3e7jkTALAcNzht9yGQuyIOtPLc4/edit#>
.

**Comment by hunterowens** [comment]
deployment gameplan: 

generate out a static monthly report, deploy via netlify

**Comment by hunterowens** [comment]
PDFs can be generate from the print option in css

**Comment by machow** [comment]
@mcplanner (cc @ryon, who is styling the report from the jarvus side), what do you think of a lineplot for service hours over a given month? 

![image](https://user-images.githubusercontent.com/2574498/121097526-f5f77300-c7a8-11eb-8a50-9fe43686e9cc.png)

This will let people see weekly trends (e.g. maybe more service hours on weekends?), and might help us report hours for agencies where they are fairly large numbers, without them crowding out each other on a calendar.

(Note: I generated fake data for this, which is why it is a saw shape :)

**Comment by mcplanner** [comment]
A chart is better than a calendar, definitely. I'm inclined to suggest a
bar chart, to show that this data is discrete rather than continuous, but
it's easier to see minor changes in the line chart. Line chart it is! Thank
you.

**Comment by machow** [comment]
Ah, nice--thanks. We could also add points, if it helps with discreteness!

![image](https://user-images.githubusercontent.com/2574498/121243065-4b945400-c86b-11eb-85b6-69dc054e28f1.png)

**Comment by mcplanner** [comment]
love it!

**Comment by machow** [comment]
Okay--great! @hunterowens, copying here the task description I sent to @ryon, so we can sync on this issue if needed. Note that if calitp can get reports done before June 15th, then they can send them in their newsletter. (may be able to use the uglier notebook version as a fallback on the 15th, it the timeline is too tight?)

**Existing report draft**

* Demo report:  https://github.com/cal-itp/reports/tree/feat-papermill/demo/output/256_0
* (note that all the data used in tables and figures is in the data folder; happy to reshape into nice formats)
* here's the html file rendered on their site: https://deploy-preview-2--cal-itp-reports.netlify.app/demo/output/256_0/report.html

**Spec**

* https://docs.google.com/document/d/1-iXNdl4f2EbYayKg3e7jkTALAcNzht9yGQuyIOtPLc4/edit#

**Task**

* Use Jinja to generate html reports based on data in the data folder.
* No need for us to worry about nbconvert, just Jinja and the data is fine.
* Where the example report and spec diverge, I would follow the spec
  - there are roughly 4 report sections, so the json files are numbered by section.
  - I can fix calculations, or do basic reshaping where useful!
  - I'll open an issue right now to check whether they're okay with the lineplot I made, rather than a calendar looking figure (since I think calendar will look weird with large numbers?)
* (Down the road they may want to send reports as emails, but the focus is html for now)

**Comment by machow** [comment]
* [CA state template](https://webstandards.ca.gov/state-template/)
* [cal-itp transit stop example](https://github.com/cal-itp/transit-stop)
* [cal-itp website](https://github.com/cal-itp/website)

**Comment by hunterowens** [comment]
* [services doc template](https://docs.google.com/document/d/1Vb4JFb4UwRqqjeQXrkwqQDOvR-vJJceMi4S1_JbnehM/edit#heading=h.luiva0fhws47) 
* [Assets / Logos etc](https://drive.google.com/drive/u/2/folders/1oBmo8UPhFjXtUArD0fliTWiuFrwtba2S)

**Comment by hunterowens** [comment]
* [homepage content to navigate to reports](https://docs.google.com/document/d/16auZ1yVciIvihZR_6P1H5xdXom_3Mf_jxyYwW-vbzrI/edit#)

**Comment by hunterowens** [comment]
these exist!
