### ISSUE TITLE
[docs] Switch to SSH cloning instead of HTTPS + PAT 

### ISSUE THREAD

**Issue by hunterowens** [cal-itp/data-infra#792]
### Current Behavior

[currently](https://docs.calitp.org/data-infra/analytics_tools/saving_code.html), the saving code docs use a github PAT + https:// based cloning. as a consequence, users have to type the PAT into the command line every time they push / pull from GH, I think. 

### Expected Behavior
I believe we should use SSH based cloning as our preffered method, allowing users to not have to enter passwords on the hub to push / pull. The GH guide is [here](https://docs.github.com/en/authentication/connecting-to-github-with-ssh)

**Comment by machow** [comment]
re-opening since the instructions as given do not allow users to push code via ssh. Let's make sure to run through new workflows when documenting

https://cal-itp.slack.com/archives/C02KH3DGZL7/p1639172356045100

**Comment by edasmalchi** [comment]
I'm working on a quick docs update to address this -- any reason to suggest analysts use an ssh passphrase?

It doesn't seem necessary to me for our setup, the linked GitHub docs seem to nudge you towards making one

(I just switched to SSH from PAT authentication following those to see if they were adequate, didn't make an ssh passphrase and working fine) Oddly didn't seem to hit the same permissions issue as Ben, but I'll add that phrase to our docs since it seemed to fix for him

**Comment by edasmalchi** [comment]
^merged PR should fix this
