### ISSUE TITLE
Duplicate feed for SolanoExpress

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-infra#893]
Thanks for the updates. In the interest of finally merging this in so the pipeline begins working, I'm going to go ahead and approve. However, I did notice that SolanoExpress and Soltrans now have the same URL, so I'm kind of wondering if we still need to keep SolanoExpress.

_Originally posted by @evansiroky in https://github.com/cal-itp/data-infra/pull/885#pullrequestreview-841086321_

**Comment by evansiroky** [comment]
@o-ram do we need to include SolanoExpress still?

**Comment by o-ram** [comment]
Good question. They're managed by Solano Transit Authority, but Soltrans and Fairfield transit operate the routes. And they use Soltrans GTFS data. (@e-lo please jump in if I'm representing this relationship incorrectly) I updated Solano Express when updating Soltrans' feeds because I'm not entirely clear on:

1. if there's any protocol to follow for completely removing an agency/service from agencies.yml
2. if in situations like this, we care about including Solano Express at all

If we consider them covered by Soltrans, I have no problems with removing them.

**Comment by evansiroky** [comment]
GTFS Feeds are now tracked in Airtable. Closing.
